obj4=read.csv("C:/Users/aditya royal/Downloads/FL_insurance_sample.csv/FL_insurance_sample.csv",header=1)
dim(obj4)
colnames(obj4)
qqnorm(log(obj4$tiv_2012))
qqline(log(obj4$tiv_2012))
hist(log(obj4$tiv_2012))
stripchart(log(obj4$tiv_2012),method='jitter')
boxplot(log(obj4$tiv_2012))
summary(log(obj4$tiv_2012))
sqrt(var(log(obj4$tiv_2012)))
for(x in colnames(obj4))
{summaries[x]=list(summary(obj4[,x]))
}
hist(log(obj4$fr_site_deductible))
